site_name: Aprendendo Python do Zero
theme:
  name: material
  language: pt-BR
  palette:
    - scheme: default
      primary: white
      accent: deep purple
  features:
    - content.code.copy        # Botão de copiar no código
    - navigation.sections      # Menu organizado
  font:
    text: Inter                # Fonte moderna e limpa
    code: Fira Code            # Fonte de código bonita

markdown_extensions:
  - admonition                 # Caixas de aviso coloridas
  - pymdownx.highlight:        # Cores no código
      anchor_linenums: true
  - pymdownx.superfences       # Blocos de código avançados

extra_css:
  - css/meu_estilo_customizado.css