site_name: Minha Documentação Keras

theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [".."]  # Aqui está a correção: de 'import_paths' para 'paths'

nav:
  - Home: index.md
  - Referência do Código: referencia.md