site_name: Keras Documentation Guide
theme:
  name: material
  language: pt-BR
  # Configuração de cores (estilo Google/Keras: Branco e Azul)
  palette:
    - scheme: default
      primary: white
      accent: indigo
  features:
    - content.code.copy          # Adiciona o botão de copiar no código
    - content.code.annotate      # Permite explicações dentro do código
    - navigation.sections        # Organiza melhor o menu lateral
    - toc.follow                 # O menu da direita segue o scroll

  # Fontes modernas (iguais às do Google)
  font:
    text: Roboto
    code: Roboto Mono

# Extensões que deixam o código e os botões bonitos
markdown_extensions:
  - attr_list                    # Necessário para os botões funcionarem
  - pymdownx.highlight:          # Cores bonitas no código
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg