site_name: Minha Documentação Keras

theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [".."]  # Aqui está a correção: de 'import_paths' para 'paths'

nav:
  - Home: index.md
  - Referência do Código: referencia.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg